//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSH_Researcher_Portal.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DareToDaSHEntities2 : DbContext
    {
        public DareToDaSHEntities2()
            : base("name=DareToDaSHEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dataset> Datasets { get; set; }
        public virtual DbSet<DS_Variables> DS_Variables { get; set; }
        public virtual DbSet<Project_Datasets> Project_Datasets { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Reseacher_Projects> Reseacher_Projects { get; set; }
        public virtual DbSet<Researcher> Researchers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Researcher_Variables> Researcher_Variables { get; set; }
        public virtual DbSet<Researcher_Documents> Researcher_Documents { get; set; }
        public virtual DbSet<Researcher_Custom_Variables> Researcher_Custom_Variables { get; set; }
        public virtual DbSet<Users_Unsecure> Users_Unsecure { get; set; }
    
        public virtual int OutputSourceDatasets_toJson_byProjectId_DatasetID(Nullable<int> prmProjectId, Nullable<int> prmProjectDatasetID)
        {
            var prmProjectIdParameter = prmProjectId.HasValue ?
                new ObjectParameter("prmProjectId", prmProjectId) :
                new ObjectParameter("prmProjectId", typeof(int));
    
            var prmProjectDatasetIDParameter = prmProjectDatasetID.HasValue ?
                new ObjectParameter("prmProjectDatasetID", prmProjectDatasetID) :
                new ObjectParameter("prmProjectDatasetID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OutputSourceDatasets_toJson_byProjectId_DatasetID", prmProjectIdParameter, prmProjectDatasetIDParameter);
        }
    }
}
