//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSH_Researcher_Portal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Variables
    {
        public int DS_VariableID { get; set; }
        public Nullable<int> DatasetID { get; set; }
        public string VarName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> CHARACTER_MAXIMUM_LENGTH { get; set; }
        public Nullable<int> Is_Identifiable { get; set; }
        public Nullable<int> Required_ForLinkage { get; set; }
        public Nullable<int> Can_Release { get; set; }
        public Nullable<int> Output_CodingID { get; set; }
        public string VarDescription { get; set; }
        public Nullable<bool> RequiredForDisplay { get; set; }
    
        public virtual Dataset Dataset { get; set; }
    }
}
