//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSH_Researcher_Portal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Researcher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Researcher()
        {
            this.Reseacher_Projects = new HashSet<Reseacher_Projects>();
        }
    
        public int ResearcherID { get; set; }
        public string ResearcherName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<int> PMD_ResearcherID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reseacher_Projects> Reseacher_Projects { get; set; }
    }
}
