//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSH_Researcher_Portal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseacher_Projects
    {
        public int ResearcherProjectsID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ResearcherID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Researcher Researcher { get; set; }
    }
}
