//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaSH_Researcher_Portal.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Researcher_Variables
    {
        public int Researcher_VariableID { get; set; }
        public Nullable<int> DS_VariableID { get; set; }
        public Nullable<int> Project_Dataset_Id { get; set; }
        public string Output_VarName { get; set; }
        public string Researcher_Comments { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsRestriction { get; set; }
        public string IsRestrictionVariabletype { get; set; }
        public string IsRestrictionMinRange { get; set; }
        public string IsRestrictionMaxRange { get; set; }
    
        public virtual Project_Datasets Project_Datasets { get; set; }
    }
}
